Enable HTML formatted notifications outside of product (migration from v2)
squaredup/Scripts pull request #1
Opened 2017-01-09 16:49 UTC by shadeon

This PR enables the ability to setup notification channels in SCOM with HTML formatting enabled, and optionally SMTP flags for importance set, without having to use Squared Up.

As such, this has been generalized to allow the SCOM web console URL to be injected as well, and no longer requires explicit cloning of an existing channel (you can create one using the script).

Included (though not specific to this script) is a Pester file for ensuring scripts meet an appropriate level of quality.  If you are on Win 10 you already have the pester module and PSScriptAnalyser modules installed, but i'd recommend updating both modules first prior to invoking the tests.

2017-01-10 23:43 UTC, clarkd requested changes

2017-01-10 23:43 UTC, clarkd commented on GenericPester.Tests.ps1
> +            It 'Has a valid signiture (if signed)' {
"signature"

2017-01-10 23:43 UTC, clarkd commented on GenericPester.Tests.ps1
> +                if ($result.Status -eq [System.Management.Automation.SignatureStatus]::NotSigned) {
Could add a test for "is signed" as all our scripts should be.

2017-01-10 23:43 UTC, clarkd commented on New-SCOMHtmlNotificationChannel.ps1
> +    Channels can either be created from scratch or clone their settings from an existing channel (and will therefore use it's predefined endpoints).
it's -> its

2017-01-10 23:43 UTC, clarkd commented on New-SCOMHtmlNotificationChannel.ps1
> +    By default notification bodies will include appropriate links to the SCOM Web console, but by specifying the SquaredUpUrl parameter links will use Squared Up instead.
Should be "web console" or "Web Console"

2017-01-10 23:43 UTC, clarkd commented on New-SCOMHtmlNotificationChannel.ps1
> +    By default notification bodies will include appropriate links to the SCOM Web console, but by specifying the SquaredUpUrl parameter links will use Squared Up instead.
"SquaredUpURL" as per parameter name, and perhaps prefix with a "-" to indicate it is a parameter.

2017-01-10 23:43 UTC, clarkd commented on New-SCOMHtmlNotificationChannel.ps1
> +    Copyright 2016 Squared Up Limited, All Rights Reserved.
2017

2017-01-10 23:43 UTC, clarkd commented on New-SCOMHtmlNotificationChannel.ps1
> +.PARAMETER SquaredUpURL
Should indicate that there should be no trailing slash.

2017-01-10 23:43 UTC, clarkd commented on New-SCOMHtmlNotificationChannel.ps1
> +            "<!-- (c) Squared Up Ltd 2016 -->",
2017

2017-01-10 23:43 UTC, clarkd commented on New-SCOMHtmlNotificationChannel.ps1
> +    $Url  = $Url.TrimEnd('/')
Ah just seen this - ignore the above :)

2017-01-11 10:31 UTC, shadeon commented on New-SCOMHtmlNotificationChannel.ps1
> +    Copyright 2016 Squared Up Limited, All Rights Reserved.
Oh god, it's 2017 already.  When did it become 2017.

2017-01-11 10:58 UTC, shadeon commented on GenericPester.Tests.ps1
> +                if ($result.Status -eq [System.Management.Automation.SignatureStatus]::NotSigned) {
Hmmm, from download.squaredup.com sure but they shouldn't be signed in-repo (contributors shouldn't be required to have a trusted code signing cert, never mind ours).

2017-01-12 11:56 UTC, clarkd approved these changes

2017-01-13 08:57 UTC, shadeon commented
@richbenwell Any thoughts on this?  Just writing up the documentation so want to know if we're good to go or further changes are required.

2017-01-17 20:22 UTC, richbenwell approved these changes

2017-01-19 08:35 UTC, merged